services:
  postgres:
    image: postgres:17
    container_name: infotecs-postgres
    environment:
      POSTGRES_DB: infotecsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d infotecsdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: InfotecsApi/Dockerfile
    container_name: infotecs-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=infotecsdb;Username=postgres;Password=psql1
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data: